import type { Server, User } from '@/types';

function generateResponseHistory(baseTime: number): number[] {
  return Array.from({ length: 24 }, () =>
    Math.max(5, Math.round(baseTime + (Math.random() - 0.5) * baseTime * 0.4)),
  );
}

export const mockServers: Server[] = [
  {
    id: 'srv-001',
    name: 'US-East API Gateway',
    ipAddress: '10.0.1.12',
    status: 'up',
    responseTime: 45,
    uptime: 99.98,
    lastChecked: new Date(Date.now() - 60_000).toISOString(),
    location: 'US-East',
    responseHistory: generateResponseHistory(45),
  },
  {
    id: 'srv-002',
    name: 'US-West Load Balancer',
    ipAddress: '10.0.2.34',
    status: 'up',
    responseTime: 62,
    uptime: 99.95,
    lastChecked: new Date(Date.now() - 120_000).toISOString(),
    location: 'US-West',
    responseHistory: generateResponseHistory(62),
  },
  {
    id: 'srv-003',
    name: 'EU-West Database Primary',
    ipAddress: '10.1.0.5',
    status: 'degraded',
    responseTime: 320,
    uptime: 92.40,
    lastChecked: new Date(Date.now() - 30_000).toISOString(),
    location: 'EU-West',
    responseHistory: generateResponseHistory(320),
  },
  {
    id: 'srv-004',
    name: 'EU-Central Auth Service',
    ipAddress: '10.1.1.18',
    status: 'up',
    responseTime: 88,
    uptime: 99.90,
    lastChecked: new Date(Date.now() - 90_000).toISOString(),
    location: 'EU-Central',
    responseHistory: generateResponseHistory(88),
  },
  {
    id: 'srv-005',
    name: 'APAC-South CDN Edge',
    ipAddress: '10.2.0.22',
    status: 'down',
    responseTime: 0,
    uptime: 34.20,
    lastChecked: new Date(Date.now() - 300_000).toISOString(),
    location: 'APAC-South',
    responseHistory: generateResponseHistory(450),
  },
  {
    id: 'srv-006',
    name: 'US-East Worker Pool',
    ipAddress: '10.0.1.45',
    status: 'up',
    responseTime: 120,
    uptime: 99.70,
    lastChecked: new Date(Date.now() - 45_000).toISOString(),
    location: 'US-East',
    responseHistory: generateResponseHistory(120),
  },
  {
    id: 'srv-007',
    name: 'US-West Cache Cluster',
    ipAddress: '10.0.2.67',
    status: 'up',
    responseTime: 15,
    uptime: 99.99,
    lastChecked: new Date(Date.now() - 20_000).toISOString(),
    location: 'US-West',
    responseHistory: generateResponseHistory(15),
  },
  {
    id: 'srv-008',
    name: 'EU-West Message Queue',
    ipAddress: '10.1.0.89',
    status: 'degraded',
    responseTime: 245,
    uptime: 89.50,
    lastChecked: new Date(Date.now() - 150_000).toISOString(),
    location: 'EU-West',
    responseHistory: generateResponseHistory(245),
  },
  {
    id: 'srv-009',
    name: 'APAC-East Search Index',
    ipAddress: '10.2.1.11',
    status: 'up',
    responseTime: 78,
    uptime: 99.85,
    lastChecked: new Date(Date.now() - 75_000).toISOString(),
    location: 'APAC-East',
    responseHistory: generateResponseHistory(78),
  },
  {
    id: 'srv-010',
    name: 'US-East Storage Gateway',
    ipAddress: '10.0.1.99',
    status: 'up',
    responseTime: 155,
    uptime: 99.60,
    lastChecked: new Date(Date.now() - 40_000).toISOString(),
    location: 'US-East',
    responseHistory: generateResponseHistory(155),
  },
  {
    id: 'srv-011',
    name: 'EU-Central Metrics Collector',
    ipAddress: '10.1.1.55',
    status: 'down',
    responseTime: 0,
    uptime: 12.80,
    lastChecked: new Date(Date.now() - 600_000).toISOString(),
    location: 'EU-Central',
    responseHistory: generateResponseHistory(200),
  },
  {
    id: 'srv-012',
    name: 'US-West ML Inference',
    ipAddress: '10.0.2.100',
    status: 'up',
    responseTime: 210,
    uptime: 99.45,
    lastChecked: new Date(Date.now() - 55_000).toISOString(),
    location: 'US-West',
    responseHistory: generateResponseHistory(210),
  },
  {
    id: 'srv-013',
    name: 'APAC-South Payment Processor',
    ipAddress: '10.2.0.77',
    status: 'up',
    responseTime: 95,
    uptime: 99.92,
    lastChecked: new Date(Date.now() - 35_000).toISOString(),
    location: 'APAC-South',
    responseHistory: generateResponseHistory(95),
  },
  {
    id: 'srv-014',
    name: 'EU-West Notification Service',
    ipAddress: '10.1.0.42',
    status: 'up',
    responseTime: 68,
    uptime: 99.78,
    lastChecked: new Date(Date.now() - 80_000).toISOString(),
    location: 'EU-West',
    responseHistory: generateResponseHistory(68),
  },
  {
    id: 'srv-015',
    name: 'US-East DNS Resolver',
    ipAddress: '10.0.1.2',
    status: 'up',
    responseTime: 8,
    uptime: 99.999,
    lastChecked: new Date(Date.now() - 10_000).toISOString(),
    location: 'US-East',
    responseHistory: generateResponseHistory(8),
  },
];

export function getServerWithJitter(server: Server): Server {
  const jitter = Math.round((Math.random() - 0.5) * server.responseTime * 0.2);
  const newResponseTime = Math.max(0, server.responseTime + jitter);

  return {
    ...server,
    responseTime: server.status === 'down' ? 0 : newResponseTime,
    lastChecked: new Date().toISOString(),
  };
}

export function getAllServersWithJitter(): Server[] {
  return mockServers.map(getServerWithJitter);
}
